In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv('data.csv')

df

,Date,Symbol,Futures Contracts,Futures Quantity,Futures Value (Rs. In Crs.),Options Contracts,Options Quantity,Options Value (Rs. In Crs.),Total Overall Value (Rs. In Crs.),Equity Traded Value (Rs. In Crs.),Speculation Ratio,Equity Traded Quantity (in Lakhs),Equity Number of Trades,Equity Total Market Cap (Rs. Crs.),options/futures,open,high,low,close
0,2016-01-01,NIFTY,81885,6141375,4890.54,859166,64437450,52040.85,56931.39,12790.77,4.450974414,8708.88,4906794,9885286.13,10.641126,7938.45,7972.55,7909.80,7963.20
1,2016-01-04,NIFTY,226345,16975875,13340.09,2546999,191024925,151788.40,165128.49,17179.35,9.612033633,11940.71,7498588,9724199.47,11.378364,7924.55,7937.55,7781.10,7791.30
2,2016-01-05,NIFTY,148669,11150175,8713.19,1945485,145911375,115647.05,124360.24,17657.69,7.042837427,14100.76,7865865,9752722.53,13.272642,7828.40,7831.20,7763.25,7784.65
3,2016-01-06,NIFTY,169347,12701025,9877.81,2131230,159842250,126551.65,136429.46,20110.22,6.784085903,12892.63,8997270,9722033.56,12.811711,7788.05,7800.95,7721.20,7741.00
4,2016-01-07,NIFTY,234900,17617500,13419.15,3324174,249313050,193468.48,206887.63,18650.32,11.09298017,11127.87,8259340,9480099.10,14.417342,7673.35,7674.95,7556.60,7568.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2594,2026-07-20,NIFTY,56686,3684590,8928.47,138857811,9025757715,21881242.72,21890171.19,107795.45,203.0713837,42777.09,34167108,48144567.04,2450.727025,24190.05,24266.10,24135.85,24238.50
2595,2026-07-21,NIFTY,50724,3297060,7984.95,327924200,21315073000,51611679.21,51619664.16,113350.33,455.3993284,42929.45,35355780,48343129.98,6463.619586,24216.05,24262.20,24135.65,24187.70
2596,2026-07-22,NIFTY,65044,4227860,10166.45,41738427,2712997755,6552201.63,6562368.08,111459.97,58.87645654,42662.67,35320601,47909998.20,644.492584,24150.45,24166.30,23961.40,23996.25
2597,2026-07-23,NIFTY,143453,9324445,22318.21,46396692,3015784980,7259056.13,7281374.34,111749.62,65.15793378,42307.80,35892377,47572808.85,325.252613,23904.80,23990.75,23807.20,23869.60
2598,2026-07-24,NIFTY,131349,8537685,20300.39,98625074,6410629810,15310648.78,15330949.17,110468.21,138.7815478,42198.45,35415629,47474922.11,754.204662,23666.35,23823.60,23606.30,23767.45

In [4]:
# 1. Ensure the column is datetime type
df['Date'] = pd.to_datetime(df['Date'])
# 2. Get the day of the week
# Option A: Day name (e.g., 'Monday', 'Tuesday')
df['day_name'] = df['Date'].dt.day_name()
# Option B: Day of week as an integer (0 = Monday, 6 = Sunday)
df['day_number'] = df['Date'].dt.dayofweek

df

,Date,Symbol,Futures Contracts,Futures Quantity,Futures Value (Rs. In Crs.),Options Contracts,Options Quantity,Options Value (Rs. In Crs.),Total Overall Value (Rs. In Crs.),Equity Traded Value (Rs. In Crs.),...,Equity Traded Quantity (in Lakhs),Equity Number of Trades,Equity Total Market Cap (Rs. Crs.),options/futures,open,high,low,close,day_name,day_number
0,2016-01-01,NIFTY,81885,6141375,4890.54,859166,64437450,52040.85,56931.39,12790.77,...,8708.88,4906794,9885286.13,10.641126,7938.45,7972.55,7909.80,7963.20,Friday,4
1,2016-01-04,NIFTY,226345,16975875,13340.09,2546999,191024925,151788.40,165128.49,17179.35,...,11940.71,7498588,9724199.47,11.378364,7924.55,7937.55,7781.10,7791.30,Monday,0
2,2016-01-05,NIFTY,148669,11150175,8713.19,1945485,145911375,115647.05,124360.24,17657.69,...,14100.76,7865865,9752722.53,13.272642,7828.40,7831.20,7763.25,7784.65,Tuesday,1
3,2016-01-06,NIFTY,169347,12701025,9877.81,2131230,159842250,126551.65,136429.46,20110.22,...,12892.63,8997270,9722033.56,12.811711,7788.05,7800.95,7721.20,7741.00,Wednesday,2
4,2016-01-07,NIFTY,234900,17617500,13419.15,3324174,249313050,193468.48,206887.63,18650.32,...,11127.87,8259340,9480099.10,14.417342,7673.35,7674.95,7556.60,7568.30,Thursday,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2594,2026-07-20,NIFTY,56686,3684590,8928.47,138857811,9025757715,21881242.72,21890171.19,107795.45,...,42777.09,34167108,48144567.04,2450.727025,24190.05,24266.10,24135.85,24238.50,Monday,0
2595,2026-07-21,NIFTY,50724,3297060,7984.95,327924200,21315073000,51611679.21,51619664.16,113350.33,...,42929.45,35355780,48343129.98,6463.619586,24216.05,24262.20,24135.65,24187.70,Tuesday,1
2596,2026-07-22,NIFTY,65044,4227860,10166.45,41738427,2712997755,6552201.63,6562368.08,111459.97,...,42662.67,35320601,47909998.20,644.492584,24150.45,24166.30,23961.40,23996.25,Wednesday,2
2597,2026-07-23,NIFTY,143453,9324445,22318.21,46396692,3015784980,7259056.13,7281374.34,111749.62,...,42307.80,35892377,47572808.85,325.252613,23904.80,23990.75,23807.20,23869.60,Thursday,3
2598,2026-07-24,NIFTY,131349,8537685,20300.39,98625074,6410629810,15310648.78,15330949.17,110468.21,...,42198.45,35415629,47474922.11,754.204662,23666.35,23823.60,23606.30,23767.45,Friday,4